language: ruby
matrix:
  include:
  - rvm: 2.2.3
  - rvm: 2.2.5
bundler_args: --without production --without development --jobs=4
cache: bundler
before_install:
  - 'echo "gem: --no-ri --no-rdoc" > ~/.gemrc'
before_script:
  - psql -c 'create user levelup with superuser;' -U postgres
  - bundle exec rake db:{create,migrate}
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - SECRET_KEY=f2fbcc06ac38f6f3a6383045f25856d
